param([Parameter(Mandatory=$false)][string]$NombreTienda = $null)
if (-not $NombreTienda) {$computerName = $env:COMPUTERNAME; if ($computerName -match 'MERLIOT') { $NombreTienda = "Merliot" } elseif ($computerName -match 'HEROES') { $NombreTienda = "Heroes" } elseif ($computerName -match 'ESCALON') { $NombreTienda = "Escalon" } else { Write-Host "No se pudo detectar la tienda. Especifica con -NombreTienda" -ForegroundColor Red; exit }}
$isAdmin = ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator); if (-not $isAdmin) {Write-Host "ERROR: Ejecuta como Administrador" -ForegroundColor Red; pause; exit}
$Username = "POS-$NombreTienda"; $Password = ConvertTo-SecureString "841357" -AsPlainText -Force
Write-Host "`n========================================" -ForegroundColor Cyan; Write-Host "CREAR USUARIO POS: $NombreTienda" -ForegroundColor Cyan; Write-Host "========================================`n" -ForegroundColor Cyan
Write-Host "[1/3] Creando usuario $Username..." -ForegroundColor Yellow
try {New-LocalUser -Name $Username -Password $Password -FullName "Usuario POS $NombreTienda" -Description "Usuario bloqueado para terminal punto de venta" -PasswordNeverExpires -UserMayNotChangePassword -ErrorAction Stop; Add-LocalGroupMember -Group "Users" -Member $Username -ErrorAction Stop; Write-Host "Usuario creado exitosamente" -ForegroundColor Green} catch {Write-Host "Error o usuario ya existe: $_" -ForegroundColor Yellow}
Write-Host "`n[2/3] Obteniendo SID del usuario..." -ForegroundColor Yellow; $user = Get-LocalUser -Name $Username; $userSID = (New-Object System.Security.Principal.NTAccount($Username)).Translate([System.Security.Principal.SecurityIdentifier]).Value; Write-Host "SID: $userSID" -ForegroundColor White
Write-Host "`n[3/3] Aplicando restricciones SOLO a $Username..." -ForegroundColor Yellow; $userHivePath = "C:\Users\$Username\NTUSER.DAT"
if (Test-Path $userHivePath) {reg load "HKU\TempPOS" $userHivePath | Out-Null; Start-Sleep -Seconds 2; $regPaths = @{"HKU\TempPOS\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer" = @{"NoControlPanel" = 1; "NoRun" = 1; "NoSettingsPage" = 1}; "HKU\TempPOS\Software\Microsoft\Windows\CurrentVersion\Policies\System" = @{"DisableRegistryTools" = 1; "DisableTaskMgr" = 1}}; foreach ($path in $regPaths.Keys) {foreach ($name in $regPaths[$path].Keys) {$value = $regPaths[$path][$name]; reg add $path /v $name /t REG_DWORD /d $value /f | Out-Null; Write-Host "[OK] $name aplicado" -ForegroundColor Green}}; Start-Sleep -Seconds 2; reg unload "HKU\TempPOS" | Out-Null; Write-Host "`nRestricciones aplicadas solo a $Username" -ForegroundColor Green} else {Write-Host "Archivo NTUSER.DAT no encontrado" -ForegroundColor Yellow; Write-Host "El usuario debe iniciar sesion una vez primero" -ForegroundColor Gray}
Write-Host "`n========================================" -ForegroundColor Cyan; Write-Host "USUARIO POS CREADO Y BLOQUEADO" -ForegroundColor Cyan; Write-Host "========================================" -ForegroundColor Cyan; Write-Host "`nUsuario: $Username" -ForegroundColor White; Write-Host "Password: 841357" -ForegroundColor White; Write-Host "`nTienda detectada: $NombreTienda" -ForegroundColor Cyan
Write-Output "Usuario $Username creado exitosamente"
